#pragma once

#include "../../interfaces/navmesh/INavmeshService.hpp"
#include "../../providers/navmesh/INavmeshProvider.hpp"
#include "../../events/navmesh/NavmeshEvents.hpp"
#include "../../events/EventTypes.hpp"
#include "NavmeshTileManager.hpp"
#include "NavmeshAgentManager.hpp"
#include <future>
#include <memory>
#include <unordered_set>

namespace services
{
    class NavmeshServiceImpl : public INavmeshService
    {
    private:
        INavmeshProvider* navmeshProvider;
        types::NavmeshBakeSettings lastBakeSettings;
        std::future<bool> bakeFuture;

        NavmeshTileManager tileManager;
        NavmeshAgentManager agentManager;

    public:
        explicit NavmeshServiceImpl(INavmeshProvider* navmeshProvider);
        ~NavmeshServiceImpl() override;

        void registerEventHandlers() override;

        void bakeNavmesh(const types::NavmeshBakeSettings& settings) override;
        types::NavmeshBakeProgress getBakeProgress() const override;

        bool saveNavmesh(const std::string& filePath) override;
        bool loadNavmesh(const std::string& filePath) override;
        bool hasNavmesh() const override;
        void clearNavmesh() override;

        // Per-tile operations (VK-739)
        bool bakeSingleTile(int tileX, int tileZ) override;
        bool saveNavmeshTiled(const std::string& directory) override;
        bool loadNavmeshTiled(const std::string& directory) override;

        navigation::NavPath findPath(const glm::vec3& start, const glm::vec3& end,
                                     float agentRadius = 0.3f, float agentHeight = 2.0f) override;
        glm::vec3 getClosestPointOnNavmesh(const glm::vec3& point, float searchRadius = 5.0f) override;
        bool isPointOnNavmesh(const glm::vec3& point, float tolerance = 0.5f) override;

        void addAgent(EntityHandle entity) override;
        void removeAgent(EntityHandle entity) override;
        void setAgentDestination(EntityHandle entity, const glm::vec3& target) override;
        void stopAgent(EntityHandle entity) override;
        void updateAgents(float deltaTime) override;

        void getNavmeshDebugMesh(std::vector<glm::vec3>& outVertices,
                                 std::vector<uint32_t>& outIndices) const override;

    private:
        void pollBakeCompletion();

        void collectSceneGeometry(const types::NavmeshBakeSettings& settings,
                                  navigation::NavmeshInputGeometry& outGeometry);
        void collectTileGeometry(const navigation::NavmeshTileBounds& bounds,
                                 const types::NavmeshBakeSettings& settings,
                                 navigation::NavmeshInputGeometry& outGeometry);
        void collectTerrainGeometry(navigation::NavmeshInputGeometry& outGeometry);
        void collectTerrainGeometryForBounds(const navigation::NavmeshTileBounds& bounds,
                                              navigation::NavmeshInputGeometry& outGeometry);
        void collectStaticMeshGeometry(navigation::NavmeshInputGeometry& outGeometry);
        void collectStaticMeshGeometryForBounds(const navigation::NavmeshTileBounds& bounds,
                                                 navigation::NavmeshInputGeometry& outGeometry);
        void collectColliderGeometry(navigation::NavmeshInputGeometry& outGeometry);
        void collectColliderGeometryForBounds(const navigation::NavmeshTileBounds& bounds,
                                               navigation::NavmeshInputGeometry& outGeometry);
        navigation::OffMeshConnectionsMap collectAllOffMeshLinks(const types::NavmeshBakeSettings& settings);
        navigation::NavmeshOffMeshConnections collectOffMeshLinksForTile(const navigation::NavmeshTileBounds& bounds,
                                                                         const types::NavmeshBakeSettings& settings);
        void drawOffMeshLinkDebug();
        void trackOffMeshLinkTransforms();
        void gatherInvokerSources();
        void drawInvokerDebug();
        void autoGenerateDropLinks(const types::NavmeshBakeSettings& settings,
                                    navigation::OffMeshConnectionsMap& outMap);

        // Obstacle support
        void collectObstacleGeometry(navigation::NavmeshInputGeometry& outGeometry);
        void collectObstacleGeometryForBounds(const navigation::NavmeshTileBounds& bounds,
                                               navigation::NavmeshInputGeometry& outGeometry);
        void trackObstacleTransforms();
        void drawObstacleDebug();
        void cleanupPhantomAgents();

        // Area modifier volume support
        navigation::AreaModifiersMap collectAllAreaModifiers();
        std::vector<navigation::NavmeshAreaModifier> collectAreaModifiersForTile(const navigation::NavmeshTileBounds& bounds);
        void trackModifierVolumeTransforms();
        void drawModifierVolumeDebug();

        // Track entity positions for dirty tile marking
        std::unordered_map<uint64_t, glm::vec3> lastOffMeshLinkPositions;
        std::unordered_map<uint64_t, glm::vec3> lastObstaclePositions;
        std::unordered_map<uint64_t, glm::vec3> lastModifierVolumePositions;
    };
}
