#include <doctest.h>

#include "test_repo_scan_helpers.hpp"

#include <graph/TerrainCompositeSnippet.hpp>
#include <terrain/TerrainAntiTiling.hpp>
#include <terrain/TerrainMaterialTypes.hpp>
#include <terrain/ValueNoise.hpp>
#include <resource/Types.hpp>
#include <resource/ShaderResource.hpp>
#include <export/ShaderCompiler.hpp>
#include "render/gpudriven/GPUDrivenTypes.hpp"
#include "render/gpudriven/terrain/TerrainCompositePermutation.hpp"
#include "render/gpudriven/terrain/TerrainLayerPBRResolver.hpp"

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <limits>
#include <string>
#include <vector>

// ============================================================
// VK-1611 - terrain anti-tiling part 1: world-anchored macro variation + distance tiling rescale.
//
// Both effects live in a GLSL snippet generated by C++ string concatenation and #include-d by BOTH
// the live terrain shader and the RVT bake shader, so nothing here can be *run* against a GPU.
// What these cases pin instead is everything that decides whether the feature is correct:
//
//   * the OFF path is an exact identity, not an approximate one;
//   * the distance signal is a UV FOOTPRINT rather than a camera distance, which is the single
//     decision that lets the camera-less bake and the live path agree at page-residency
//     boundaries - so the footprint arithmetic is mirrored on the CPU and checked;
//   * every scalar that reaches the GPU is clamped at one seam (resolveTerrainAntiTiling), and two
//     of those clamps are correctness invariants rather than taste;
//   * the permutation flags are derived from those CLAMPED values, so an out-of-range number an
//     artist typed cannot switch a shader permutation on.
//
// CPU-only: no Vulkan device, no window.
// ============================================================

namespace
{
    namespace fs = std::filesystem;
    using editor::graph::buildTerrainCompositeLoop;
    using editor::graph::buildTerrainCompositeSnippet;
    using render::gpudriven::TerrainAntiTilingGPUData;
    using render::gpudriven::resolveTerrainAntiTiling;
    using render::gpudriven::terrainMaterialWantsDistanceRescale;
    using render::gpudriven::terrainMaterialWantsMacroVariation;

    fs::path repoRoot()
    {
        const auto root = repo_scan::findRepoRoot();
        REQUIRE_MESSAGE(root.has_value(), "could not locate the repo root from Tests.exe");
        return *root;
    }

    size_t countOccurrences(const std::string& haystack, const std::string& needle)
    {
        if (needle.empty()) return 0;
        size_t count = 0;
        for (size_t pos = haystack.find(needle); pos != std::string::npos;
             pos = haystack.find(needle, pos + needle.size()))
        {
            ++count;
        }
        return count;
    }
}

TEST_SUITE("TerrainAntiTiling")
{
    // ------------------------------------------------------------------
    // 1. Macro variation: the OFF path is EXACT.
    // ------------------------------------------------------------------

    TEST_CASE("macro variation at strength 0 is exactly 1.0 for every input")
    {
        // THE reason this feature needs no correctness gate: at strength 0 both factors collapse to
        // exactly 1.0 and their product is exactly 1.0, so `mat_albedo *= macro` cannot perturb a
        // single bit. `==` on floats is deliberate - "close to 1" would not be good enough, because
        // the claim being made is that terrain without macro variation renders identically.
        for (float n0 = 0.0f; n0 <= 1.0f; n0 += 0.125f)
        {
            for (float n1 = 0.0f; n1 <= 1.0f; n1 += 0.125f)
            {
                CAPTURE(n0);
                CAPTURE(n1);
                CHECK(terrain::macroVariation(n0, n1, 0.0f) == 1.0f);
            }
        }
    }

    TEST_CASE("macro variation is centred on 1.0, so it does not darken or brighten the terrain")
    {
        // Each octave is remapped from [0,1] to a multiplier around 1, so the average albedo is
        // preserved. Without this a strength slider would double as an exposure slider.
        double sum = 0.0;
        int samples = 0;
        for (int i = 0; i < 64; ++i)
        {
            for (int j = 0; j < 64; ++j)
            {
                const float n0 = static_cast<float>(i) / 63.0f;
                const float n1 = static_cast<float>(j) / 63.0f;
                sum += terrain::macroVariation(n0, n1, 1.0f);
                ++samples;
            }
        }
        CHECK(sum / samples == doctest::Approx(1.0).epsilon(0.01));
    }

    TEST_CASE("macro variation stays positive across the whole strength range")
    {
        // A negative multiplier would flip albedo, and a zero one would punch black holes. With
        // both octaves at their minimum and strength at its maximum the factor bottoms out at
        // 0.5 * 0.5 = 0.25.
        const float worst = terrain::macroVariation(0.0f, 0.0f, terrain::MACRO_VARIATION_MAX_STRENGTH);
        CHECK(worst == doctest::Approx(0.25f));
        CHECK(worst > 0.0f);
        const float best = terrain::macroVariation(1.0f, 1.0f, terrain::MACRO_VARIATION_MAX_STRENGTH);
        CHECK(best == doctest::Approx(2.25f));
    }

    // ------------------------------------------------------------------
    // 2. The distance signal.
    // ------------------------------------------------------------------

    TEST_CASE("footprintLog2 is log2 of the LONGER derivative, not the shorter one")
    {
        // Deliberately rho_MAX, with no division by the anisotropy ratio. Vulkan's lambda_base
        // divides by eta and so tracks the MINOR axis; under the grazing view an RTS camera has all
        // the time, that reports "near" for ground that is in fact far away and heavily minified.
        CHECK(terrain::footprintLog2(1.0f, 0.0f, 0.0f, 1.0f) == doctest::Approx(0.0f));
        CHECK(terrain::footprintLog2(0.5f, 0.0f, 0.0f, 0.5f) == doctest::Approx(-1.0f));

        // Strongly anisotropic: the long axis is 1, the short axis is 1/256. Taking the max gives
        // 0; taking the min would give -8, i.e. eight stops of "this is close up".
        CHECK(terrain::footprintLog2(1.0f, 0.0f, 0.0f, 1.0f / 256.0f) == doctest::Approx(0.0f));
    }

    TEST_CASE("footprintLog2 survives a degenerate derivative")
    {
        // A zero-area quad would otherwise reach log2(0) and produce -inf, which smoothstep would
        // turn into a NaN blend factor and paint the layer black.
        const float fp = terrain::footprintLog2(0.0f, 0.0f, 0.0f, 0.0f);
        CHECK(std::isfinite(fp));
        CHECK(fp < 0.0f);
    }

    TEST_CASE("a layer's footprint is the base footprint shifted by log2(tilingScale)")
    {
        // This exactness is what lets ONE material-global knee be correct for layers that tile at
        // wildly different rates: the composite adds log2(tilingScale) rather than re-deriving the
        // gradients, because layerUVdx is literally triplanarWorldUVdx * tilingScale.
        const float base = terrain::footprintLog2(0.25f, 0.0f, 0.0f, 0.25f); // -2
        CHECK(base == doctest::Approx(-2.0f));

        CHECK(terrain::layerFootprintLog2(base, 1.0f) == doctest::Approx(-2.0f));
        CHECK(terrain::layerFootprintLog2(base, 2.0f) == doctest::Approx(-1.0f));  // twice the repeats
        CHECK(terrain::layerFootprintLog2(base, 0.5f) == doctest::Approx(-3.0f));  // half

        // Equivalent to scaling the derivatives directly.
        CHECK(terrain::layerFootprintLog2(base, 8.0f)
              == doctest::Approx(terrain::footprintLog2(2.0f, 0.0f, 0.0f, 2.0f)));
    }

    // ------------------------------------------------------------------
    // 3. The rescale blend.
    // ------------------------------------------------------------------

    TEST_CASE("the distance rescale blend is 0 before the knee and saturates after it")
    {
        const float knee = terrain::DISTANCE_RESCALE_DEFAULT_KNEE;   // -7
        const float width = terrain::DISTANCE_RESCALE_DEFAULT_WIDTH; // 2

        CHECK(terrain::distanceRescaleBlend(knee - 1.0f, knee, width, 1.0f) == 0.0f);
        CHECK(terrain::distanceRescaleBlend(knee, knee, width, 1.0f) == 0.0f);
        CHECK(terrain::distanceRescaleBlend(knee + width, knee, width, 1.0f) == doctest::Approx(1.0f));
        CHECK(terrain::distanceRescaleBlend(knee + 10.0f, knee, width, 1.0f) == doctest::Approx(1.0f));
        CHECK(terrain::distanceRescaleBlend(knee + 0.5f * width, knee, width, 1.0f)
              == doctest::Approx(0.5f));

        // Monotonic across the fade, so the transition cannot double back and shimmer.
        float previous = -1.0f;
        for (float fp = knee - 1.0f; fp <= knee + width + 1.0f; fp += 0.1f)
        {
            const float t = terrain::distanceRescaleBlend(fp, knee, width, 1.0f);
            CHECK(t >= previous);
            previous = t;
        }
    }

    TEST_CASE("strength scales the rescale blend and 0 disables it everywhere")
    {
        const float knee = terrain::DISTANCE_RESCALE_DEFAULT_KNEE;
        const float width = terrain::DISTANCE_RESCALE_DEFAULT_WIDTH;
        for (float fp = knee - 2.0f; fp <= knee + width + 2.0f; fp += 0.25f)
        {
            CAPTURE(fp);
            CHECK(terrain::distanceRescaleBlend(fp, knee, width, 0.0f) == 0.0f);
            CHECK(terrain::distanceRescaleBlend(fp, knee, width, 0.5f)
                  == doctest::Approx(0.5f * terrain::distanceRescaleBlend(fp, knee, width, 1.0f)));
        }
    }

    // ------------------------------------------------------------------
    // 4. The resolver: the one seam where authored intent becomes a GPU scalar.
    // ------------------------------------------------------------------

    TEST_CASE("resolveTerrainAntiTiling clamps everything that reaches the GPU")
    {
        SUBCASE("defaults resolve to both features OFF")
        {
            const auto p = resolveTerrainAntiTiling(terrain::TerrainAntiTilingSettings{});
            CHECK(p.macroStrength == 0.0f);
            CHECK(p.rescaleStrength == 0.0f);
            CHECK_FALSE(terrainMaterialWantsMacroVariation(p));
            CHECK_FALSE(terrainMaterialWantsDistanceRescale(p));
        }

        SUBCASE("a non-positive macro size cannot upload an infinite frequency")
        {
            // The uploaded scalar is the RECIPROCAL of the authored size, so this clamp is a
            // correctness invariant, not a range check - the same class of bound as VK-1609's
            // MAX_HEIGHT_BLEND_CONTRAST.
            terrain::TerrainAntiTilingSettings s;
            s.macroVariationSize0 = 0.0f;
            s.macroVariationSize1 = -50.0f;
            const auto p = resolveTerrainAntiTiling(s);
            CHECK(std::isfinite(p.macroFrequency0));
            CHECK(std::isfinite(p.macroFrequency1));
            CHECK(p.macroFrequency0 > 0.0f);
            CHECK(p.macroFrequency1 > 0.0f);
            CHECK(p.macroFrequency0 == doctest::Approx(1.0f / terrain::MACRO_VARIATION_MIN_SIZE));
        }

        SUBCASE("the fade width is clamped away from zero")
        {
            // The shader feeds this straight to smoothstep, whose behaviour with equal edges is
            // undefined - in practice a division by zero.
            terrain::TerrainAntiTilingSettings s;
            s.distanceRescaleWidth = 0.0f;
            const auto p = resolveTerrainAntiTiling(s);
            CHECK(p.rescaleWidthLog2 >= terrain::DISTANCE_RESCALE_MIN_WIDTH);
            CHECK(p.rescaleWidthLog2 > 0.0f);
        }

        SUBCASE("out-of-range strengths and scales are pulled into range")
        {
            terrain::TerrainAntiTilingSettings s;
            s.macroVariationStrength = 12.0f;
            s.distanceRescaleStrength = -3.0f;
            s.distanceRescaleScale = 900.0f;
            s.distanceRescaleKnee = -900.0f;
            const auto p = resolveTerrainAntiTiling(s);
            CHECK(p.macroStrength == terrain::MACRO_VARIATION_MAX_STRENGTH);
            CHECK(p.rescaleStrength == 0.0f);
            CHECK(p.rescaleScale == terrain::DISTANCE_RESCALE_MAX_SCALE);
            CHECK(p.rescaleKneeLog2 == terrain::DISTANCE_RESCALE_MIN_KNEE);
        }

        SUBCASE("sizes are inverted into frequencies, not passed through")
        {
            terrain::TerrainAntiTilingSettings s;
            s.macroVariationSize0 = 250.0f;
            const auto p = resolveTerrainAntiTiling(s);
            CHECK(p.macroFrequency0 == doctest::Approx(1.0f / 250.0f));
        }
    }

    TEST_CASE("the permutation flags are derived from the CLAMPED scalars")
    {
        SUBCASE("macro variation switches on with any positive strength")
        {
            terrain::TerrainAntiTilingSettings s;
            s.macroVariationStrength = 0.01f;
            CHECK(terrainMaterialWantsMacroVariation(resolveTerrainAntiTiling(s)));
        }

        SUBCASE("a negative authored strength resolves to OFF, not to a compiled no-op")
        {
            terrain::TerrainAntiTilingSettings s;
            s.macroVariationStrength = -1.0f;
            CHECK_FALSE(terrainMaterialWantsMacroVariation(resolveTerrainAntiTiling(s)));
        }

        SUBCASE("a far scale of exactly 1 counts as OFF")
        {
            // The one configuration where the feature is provably pure cost: the far tap would
            // sample the same texels as the near one, so the material would pay a full extra
            // textureGrad per layer to blend a value with itself.
            terrain::TerrainAntiTilingSettings s;
            s.distanceRescaleStrength = 1.0f;
            s.distanceRescaleScale = 1.0f;
            CHECK_FALSE(terrainMaterialWantsDistanceRescale(resolveTerrainAntiTiling(s)));

            s.distanceRescaleScale = 0.25f;
            CHECK(terrainMaterialWantsDistanceRescale(resolveTerrainAntiTiling(s)));
        }
    }

    // ------------------------------------------------------------------
    // 5. The value noise, whose whole point is that it ports to GLSL exactly.
    // ------------------------------------------------------------------

    TEST_CASE("valueNoise2D stays in [0,1] and is deterministic")
    {
        // Procedural rather than a macro TEXTURE precisely so this is assertable: every operation
        // is 32-bit unsigned integer arithmetic, which wraps identically in GLSL, and the final
        // divide by 0xFFFFFF is exact in FP32 (2^24-1 is the largest exactly-representable
        // integer). A texture fetch could never be checked here.
        for (int i = -40; i <= 40; ++i)
        {
            for (int j = -40; j <= 40; ++j)
            {
                const float x = static_cast<float>(i) * 0.37f;
                const float z = static_cast<float>(j) * 0.41f;
                const float n = terrain::valueNoise2D(x, z, 0u);
                CAPTURE(x);
                CAPTURE(z);
                CHECK(n >= 0.0f);
                CHECK(n <= 1.0f);
                CHECK(terrain::valueNoise2D(x, z, 0u) == n); // pure function
            }
        }
    }

    TEST_CASE("valueNoise2D is continuous across cell boundaries")
    {
        // The composite multiplies albedo by this, so a discontinuity would draw a visible grid -
        // the very artifact macro variation exists to hide.
        for (float t = -0.02f; t <= 0.02f; t += 0.002f)
        {
            const float a = terrain::valueNoise2D(3.0f + t, 5.25f, 7u);
            const float b = terrain::valueNoise2D(3.0f + t + 0.001f, 5.25f, 7u);
            CHECK(std::fabs(a - b) < 0.05f);
        }
    }

    TEST_CASE("the two macro octaves are decorrelated by their seeds")
    {
        // The composite derives octave 1's seed as `macroSeed ^ 0x9E3779B9u`. If that were dropped
        // the two octaves would still differ (different frequencies), but at any point where the
        // frequencies happened to coincide they would multiply their own value and produce a
        // squared, higher-contrast pattern.
        int differing = 0;
        for (int i = 0; i < 200; ++i)
        {
            const float x = static_cast<float>(i) * 0.13f;
            const float a = terrain::valueNoise2D(x, 1.0f, 5u);
            const float b = terrain::valueNoise2D(x, 1.0f, 5u ^ 0x9E3779B9u);
            if (std::fabs(a - b) > 1e-4f) ++differing;
        }
        CHECK(differing > 190);
    }

    // ------------------------------------------------------------------
    // 6. What the emitter actually emits.
    // ------------------------------------------------------------------

    TEST_CASE("the rescale arm adds exactly one albedo fetch and nothing else")
    {
        for (bool detail : {false, true})
        {
            CAPTURE(detail);
            const std::string base = buildTerrainCompositeLoop(detail, /*heightBlend=*/false);
            const std::string rescale =
                buildTerrainCompositeLoop(detail, /*heightBlend=*/false, /*distanceRescale=*/true);

            // The story's cost claim, in executable form: ALBEDO only. Widening it to the normal or
            // ORM fetches would double the whole composite instead of adding 25%.
            CHECK(countOccurrences(rescale, "textureGrad(") ==
                  countOccurrences(base, "textureGrad(") + 1u);
            CHECK(countOccurrences(rescale, "nonuniformEXT(albedoIdx)") == 2u);
            CHECK(countOccurrences(rescale, "nonuniformEXT(ormIdx)") == 1u);
            if (detail)
            {
                CHECK(countOccurrences(rescale, "nonuniformEXT(normalIdx)") == 1u);
                CHECK(countOccurrences(rescale, "nonuniformEXT(emissionIdx)") == 1u);
            }

            // Branchless, and no new branch anywhere: the explicit-gradient (textureGrad) contract
            // the composite documents rests on the control flow not getting worse.
            CHECK(countOccurrences(rescale, "if (") == countOccurrences(base, "if ("));
            CHECK(countOccurrences(rescale, "continue;") == countOccurrences(base, "continue;"));
            CHECK(rescale.find("smoothstep(terrainAntiTiling.rescaleKneeLog2") != std::string::npos);

            // The far tap must carry TRANSFORMED gradients. Reusing layerUVdx/dy for a rescaled UV
            // would ask the hardware for the wrong mip and shimmer under motion.
            CHECK(rescale.find("layerFarUVdx = layerUVdx * terrainAntiTiling.rescaleScale")
                  != std::string::npos);
            CHECK(rescale.find("layerFarUVdy = layerUVdy * terrainAntiTiling.rescaleScale")
                  != std::string::npos);

            // ...and none of it leaks into the arm that did not ask for it.
            CHECK(base.find("terrainAntiTiling") == std::string::npos);
            CHECK(base.find("layerFarUV") == std::string::npos);
        }
    }

    TEST_CASE("macro variation modulates albedo but never emission")
    {
        // Both arms compute mat_emission FROM mat_albedo, so placing the tail after the permutation
        // chain is what keeps a reflectance tint from also scaling a light source. If it ever moved
        // inside buildTerrainCompositeLoop this would catch it - and so would the golden strings.
        const std::string tail = editor::graph::buildTerrainMacroVariationSnippet();
        CHECK(tail.find("mat_albedo *=") != std::string::npos);
        CHECK(tail.find("mat_emission") == std::string::npos);

        const std::string snippet = buildTerrainCompositeSnippet();
        const size_t tailPos = snippet.find(tail);
        REQUIRE(tailPos != std::string::npos);
        for (unsigned mask = 0; mask < 16u; ++mask)
        {
            const std::string arm = buildTerrainCompositeLoop((mask & 1u) != 0, (mask & 2u) != 0,
                                                              (mask & 4u) != 0, (mask & 8u) != 0);
            CAPTURE(mask);
            CHECK_MESSAGE(snippet.find(arm) < tailPos, "an arm body follows the macro-variation tail");
        }
    }

    TEST_CASE("macro variation is world-anchored, not UV-anchored")
    {
        // triplanarWorldUV is already multiplied by textureScale AND triplanar-blended inside
        // caves, so keying off it would make the pattern slide with the texture scale and warp on
        // cave walls - and, worse, disagree between the bake (flat, top-down) and the live path.
        const std::string tail = editor::graph::buildTerrainMacroVariationSnippet();
        CHECK(countOccurrences(tail, "terrainWorldXZ") == 2u);
        CHECK(tail.find("triplanarWorldUV") == std::string::npos);
        CHECK(tail.find("layerUV") == std::string::npos);
    }

    // ------------------------------------------------------------------
    // 7. Both composite consumers honour the contract.
    // ------------------------------------------------------------------

    TEST_CASE("both includers define every contract variable the composite reads")
    {
        // The generated snippet is #include-d INSIDE main() by two hand-written shaders. A
        // variable added to the contract and wired into only one of them compiles fine in the
        // shader that has it and breaks the other - and if that other one is the bake, the symptom
        // is baked pages silently disagreeing with the live fallback.
        const fs::path shaders = repoRoot() / "resources" / "shaders" / "gpudriven";
        const std::string live = repo_scan::readFile(shaders / "mesh_terrain.glsl");
        const std::string bake = repo_scan::readFile(shaders / "terrain_rvt_bake.glsl");
        REQUIRE_FALSE(live.empty());
        REQUIRE_FALSE(bake.empty());

        for (const char* name : {"terrainWorldXZ", "terrainFootprintLog2", "terrainAntiTiling"})
        {
            CAPTURE(name);
            CHECK_MESSAGE(live.find(name) != std::string::npos, "mesh_terrain.glsl lacks " << name);
            CHECK_MESSAGE(bake.find(name) != std::string::npos, "terrain_rvt_bake.glsl lacks " << name);
        }

        // The value-noise helper must be included at FILE scope by both: the snippet sits inside
        // main() and cannot declare functions.
        CHECK(live.find("terrain_value_noise.glsl") != std::string::npos);
        CHECK(bake.find("terrain_value_noise.glsl") != std::string::npos);

        // Both must bind the anti-tiling block, at the set index each pipeline uses for the
        // weight-map descriptor set: 1 live, 0 in the bake's compact three-set layout.
        CHECK(live.find("set = 1, binding = 2) readonly buffer TerrainAntiTilingBuffer") != std::string::npos);
        CHECK(bake.find("set = 0, binding = 2) readonly buffer TerrainAntiTilingBuffer") != std::string::npos);
    }

    TEST_CASE("mesh_terrain.glsl's fragment stage compiles with the composite's contract")
    {
        // The other composite consumer. The suite has never compiled it — the note in
        // test_terrain_height_blend.cpp rules it out because the TASK and MESH stages need
        // GL_EXT_mesh_shader and the full 14-set layout. But the FRAGMENT stage is where every
        // edit in this story landed (the contract variables, the RVT-mip parity block, the
        // anti-tiling binding, the two file-scope includes), and it compiles standalone. Without
        // this, a contract variable wired into the bake and forgotten here would only surface when
        // someone opened a terrain scene in the Editor.
        const fs::path shaderDir = repoRoot() / "resources" / "shaders" / "gpudriven";
        const fs::path shaderPath = shaderDir / "mesh_terrain.glsl";
        REQUIRE_MESSAGE(fs::exists(shaderPath), "missing " << shaderPath.string());

        const auto stages = resource::ShaderResource::readShaderFile(shaderPath.string());
        REQUIRE_MESSAGE(!stages.empty(), "no #type stages parsed from " << shaderPath.string());

        // RVT off and on, because the RVT branch carries the fallback footprint override, crossed
        // with the composite flags that reach into the fragment body.
        const std::vector<std::vector<std::string>> configs = {
            {},
            {"TERRAIN_DETAIL_MAPS", "TERRAIN_HEIGHT_BLEND", "TERRAIN_DISTANCE_RESCALE",
             "TERRAIN_HEX_TILING", "TERRAIN_MACRO_VARIATION"},
            {"RVT_ENABLED"},
            {"RVT_ENABLED", "TERRAIN_DETAIL_MAPS"},
            {"RVT_ENABLED", "TERRAIN_DISTANCE_RESCALE"},
            {"RVT_ENABLED", "TERRAIN_HEX_TILING"},
            {"RVT_ENABLED", "TERRAIN_MACRO_VARIATION"},
            {"RVT_ENABLED", "TERRAIN_DETAIL_MAPS", "TERRAIN_HEIGHT_BLEND",
             "TERRAIN_DISTANCE_RESCALE", "TERRAIN_HEX_TILING", "TERRAIN_MACRO_VARIATION"},
            // VK-1614 local weather. These are LIVE-ONLY macros — they gate code after the
            // RVT-resolve / live-composite join, so the bake never sees them and this shader is the
            // only place they can break. Each alone (the weather block is a chain of independent
            // #ifdefs, so a typo in one arm is invisible with the others on), then together, then
            // crossed with RVT (the response gather runs in the resolved path too, which is the
            // whole reason it is a separate loop rather than composite accumulators).
            {"TERRAIN_WEATHER_RESPONSE"},
            {"TERRAIN_WEATHER_MASK"},
            {"TERRAIN_PUDDLES"},
            {"TERRAIN_WEATHER_RESPONSE", "TERRAIN_WEATHER_MASK", "TERRAIN_PUDDLES"},
            {"RVT_ENABLED", "TERRAIN_WEATHER_RESPONSE", "TERRAIN_WEATHER_MASK", "TERRAIN_PUDDLES"},
            {"RVT_ENABLED", "TERRAIN_DETAIL_MAPS", "TERRAIN_HEIGHT_BLEND",
             "TERRAIN_DISTANCE_RESCALE", "TERRAIN_HEX_TILING", "TERRAIN_MACRO_VARIATION",
             "TERRAIN_WEATHER_RESPONSE", "TERRAIN_WEATHER_MASK", "TERRAIN_PUDDLES"},
        };

        bool sawFragment = false;
        for (const auto& macros : configs)
        {
            shaderCompiler::CompileOptions options;
            options.includeBasePath = shaderDir;
            options.macroNames = macros;

            std::string label;
            for (const auto& m : macros) { label += "+"; label += m; }
            CAPTURE(label);

            for (const auto& stage : stages)
            {
                if (stage.type != resource::ShaderType::FRAGMENT)
                    continue;
                sawFragment = true;
                const auto vkStage =
                    shaderCompiler::shaderTypeToVulkanStage(static_cast<uint8_t>(stage.type));
                const auto spirv =
                    shaderCompiler::compile(stage.source, vkStage, "mesh_terrain.glsl:frag" + label, options);
                CHECK_MESSAGE(!spirv.empty(), "failed to compile mesh_terrain.glsl fragment" << label);
            }
        }
        CHECK(sawFragment);
    }

    TEST_CASE("the composite permutation is applied from one shared definition")
    {
        using render::gpudriven::TerrainCompositePermutation;

        // A tiny stand-in for core::Shader. applyTerrainCompositeMacros is templated precisely so
        // this is possible without a Vulkan device - and having ONE definition of "which macros"
        // is what stops the live pipeline and the RVT baker from drifting apart.
        struct FakeShader
        {
            std::vector<std::string> macros;
            void addMacroDefinition(const std::string& m) { macros.push_back(m); }
        };

        SUBCASE("a default permutation defines nothing")
        {
            FakeShader s;
            render::gpudriven::applyTerrainCompositeMacros(s,TerrainCompositePermutation{});
            CHECK(s.macros.empty());
        }

        SUBCASE("every flag maps to exactly one macro")
        {
            TerrainCompositePermutation p;
            p.detailMaps = true;
            p.heightBlend = true;
            p.distanceRescale = true;
            p.hexTiling = true;
            p.macroVariation = true;
            FakeShader s;
            render::gpudriven::applyTerrainCompositeMacros(s,p);
            CHECK(s.macros.size() == 5u);
            for (const char* m : {"TERRAIN_DETAIL_MAPS", "TERRAIN_HEIGHT_BLEND",
                                  "TERRAIN_DISTANCE_RESCALE", "TERRAIN_HEX_TILING",
                                  "TERRAIN_MACRO_VARIATION"})
            {
                CAPTURE(m);
                CHECK(std::find(s.macros.begin(), s.macros.end(), m) != s.macros.end());
            }
        }

        SUBCASE("equality compares every flag, so a partial copy cannot pass as unchanged")
        {
            TerrainCompositePermutation a;
            TerrainCompositePermutation b;
            CHECK(a == b);
            b.hexTiling = true;
            CHECK_FALSE(a == b);
        }
    }
}
