#include <doctest.h>

#include "test_repo_scan_helpers.hpp"
#include "test_terrain_height_blend_golden.hpp"

#include <graph/TerrainCompositeSnippet.hpp>
#include <terrain/TerrainHeightBlend.hpp>
#include <terrain/TerrainMaterialTypes.hpp>
#include <texture/OrmTexturePacker.hpp>
#include <resource/Types.hpp>
#include <resource/ShaderResource.hpp>
#include <export/ShaderCompiler.hpp>
#include "render/gpudriven/GPUDrivenTypes.hpp"
#include "render/gpudriven/terrain/TerrainLayerPBRResolver.hpp"
#include "render/material/MaterialPBRExtractor.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <regex>
#include <string>
#include <vector>

// ============================================================
// VK-1609 - terrain height-blended layer compositing, with per-layer height packed in ORM alpha.
//
// The blend runs on the GPU, inside a GLSL snippet that is GENERATED by C++ string concatenation
// (editor/graph/TerrainCompositeSnippet.hpp) and written to the checked-in
// resources/shaders/material/terrain_material_generated.glsl, which BOTH the live terrain fragment
// shader and the RVT bake shader #include verbatim. None of that can be *run* from a GPU-free test
// suite, so these cases pin it by construction instead:
//
//   * The LINEAR arms of the emitter are compared byte-for-byte against text captured from the
//     pre-VK-1609 generator. That is the executable form of the story's "layers without a height
//     map fall back to linear blend bit-identical to today's output" criterion - a future edit that
//     perturbs the fallback fails the build instead of shifting pixels quietly.
//   * Every permutation of the generated snippet is compiled to SPIR-V through shaderc. This is the
//     only automated proof that all four arms are valid GLSL and that the new TerrainLayerGPUData
//     field actually resolves against gpu_types.glsl.
//   * The C++ mirror of the blend arithmetic (terrain::heightBlendWeight) is checked for exact
//     bit-identity at contrast 0, which is the property the whole fallback guarantee rests on.
//   * The C++ struct and its GLSL mirror are cross-checked field by field. Nothing else in the
//     suite does this, and a one-sided edit silently corrupts every terrain layer.
//
// CPU-only: no Vulkan device, no window. shaderCompiler::compile is plain shaderc.
// ============================================================

namespace
{
    namespace fs = std::filesystem;
    using editor::graph::buildTerrainCompositeLoop;
    using editor::graph::buildTerrainCompositeSnippet;

    fs::path repoRoot()
    {
        const auto root = repo_scan::findRepoRoot();
        REQUIRE_MESSAGE(root.has_value(), "could not locate the repo root from Tests.exe");
        return *root;
    }

    size_t countOccurrences(const std::string& haystack, const std::string& needle)
    {
        size_t n = 0;
        for (size_t pos = haystack.find(needle); pos != std::string::npos;
             pos = haystack.find(needle, pos + needle.size()))
        {
            ++n;
        }
        return n;
    }

    // The generated file is written by std::ofstream in TEXT mode, so it lands CRLF on Windows
    // while the emitter produces LF. Compare content, not line-ending policy.
    std::string normalizeNewlines(std::string s)
    {
        s.erase(std::remove(s.begin(), s.end(), '\r'), s.end());
        return s;
    }

    std::vector<std::string> splitLines(const std::string& s)
    {
        std::vector<std::string> out;
        std::string cur;
        for (char c : s)
        {
            if (c == '\n') { out.push_back(cur); cur.clear(); }
            else cur += c;
        }
        if (!cur.empty()) out.push_back(cur);
        return out;
    }

    // Line-by-line first: a whole-blob mismatch on a 70-line string prints unusably.
    void checkTextEqual(const std::string& got, const std::string& want)
    {
        const auto g = splitLines(got);
        const auto w = splitLines(want);
        CHECK(g.size() == w.size());
        for (size_t i = 0; i < std::min(g.size(), w.size()); ++i)
        {
            CHECK_MESSAGE(g[i] == w[i],
                          "line " << (i + 1) << ":\n  got  [" << g[i] << "]\n  want [" << w[i] << "]");
        }
        CHECK(got == want);
    }

    // A single-mip grayscale TextureData in the RGBA8 layout the ORM packer expects.
    resource::TextureData makeGray(uint32_t w, uint32_t h, const std::vector<uint8_t>& values)
    {
        REQUIRE(values.size() == static_cast<size_t>(w) * h);
        resource::TextureData t;
        t.width = w;
        t.height = h;
        t.numbersOfChannels = 4;
        t.mipLevels = 1;
        resource::MipLevelData mip;
        mip.width = w;
        mip.height = h;
        mip.data.resize(static_cast<size_t>(w) * h * 4);
        for (size_t i = 0; i < values.size(); ++i)
        {
            // getGrayscaleValue reads the RED byte only; fill the rest so the data is well-formed.
            mip.data[i * 4 + 0] = values[i];
            mip.data[i * 4 + 1] = values[i];
            mip.data[i * 4 + 2] = values[i];
            mip.data[i * 4 + 3] = 255;
        }
        t.mipData.push_back(std::move(mip));
        return t;
    }

    struct DecodedMip
    {
        uint32_t width = 0;
        uint32_t height = 0;
        std::vector<uint8_t> bgra; // exactly as stored on disk
    };

    // Minimal .vfImage reader for the uncompressed case, matching OrmTexturePacker's writer.
    // Deliberately hand-rolled rather than routed through the engine loader: what VK-1609 depends
    // on is the ON-DISK byte layout carrying a real alpha, so that is what this asserts.
    std::vector<DecodedMip> readVfImageMips(const fs::path& path)
    {
        std::ifstream f(path, std::ios::binary);
        REQUIRE_MESSAGE(f.is_open(), "missing " << path.string());

        auto u8 = [&] { uint8_t v = 0; f.read(reinterpret_cast<char*>(&v), 1); return v; };
        auto u32 = [&] {
            uint8_t b[4]{};
            f.read(reinterpret_cast<char*>(b), 4);
            return static_cast<uint32_t>(b[0]) | (static_cast<uint32_t>(b[1]) << 8) |
                   (static_cast<uint32_t>(b[2]) << 16) | (static_cast<uint32_t>(b[3]) << 24);
        };

        u8();                        // file type
        u32(); u32(); u32();         // version major / minor / patch
        u32(); u32();                // width / height
        u32();                       // channel count
        const uint32_t mipLevels = u32();
        const uint8_t compression = u8();
        REQUIRE_MESSAGE(compression == 0, "this test packs uncompressed on purpose");

        std::vector<DecodedMip> mips;
        for (uint32_t i = 0; i < mipLevels; ++i)
        {
            DecodedMip m;
            m.width = u32();
            m.height = u32();
            const uint32_t dataSize = u32();
            m.bgra.resize(dataSize);
            f.read(reinterpret_cast<char*>(m.bgra.data()), dataSize);
            mips.push_back(std::move(m));
        }
        return mips;
    }
}

TEST_SUITE("TerrainHeightBlend")
{
    // ------------------------------------------------------------------
    // 1. The linear arms are byte-identical to the pre-VK-1609 emitter.
    // ------------------------------------------------------------------

    TEST_CASE("linear composite arms are byte-identical to the pre-VK-1609 generator")
    {
        SUBCASE("TERRAIN_DETAIL_MAPS arm")
        {
            checkTextEqual(buildTerrainCompositeLoop(/*detail=*/true, /*heightBlend=*/false),
                           terrain_composite_golden::DETAIL_LINEAR);
        }

        SUBCASE("non-detail arm")
        {
            checkTextEqual(buildTerrainCompositeLoop(/*detail=*/false, /*heightBlend=*/false),
                           terrain_composite_golden::PLAIN_LINEAR);
        }
    }

    // ------------------------------------------------------------------
    // 2. Height-arm invariants.
    // ------------------------------------------------------------------

    TEST_CASE("height-blend arm adds no texture fetch and keeps the raw-weight cull")
    {
        for (bool detail : {false, true})
        {
            CAPTURE(detail);
            const std::string linear = buildTerrainCompositeLoop(detail, /*heightBlend=*/false);
            const std::string height = buildTerrainCompositeLoop(detail, /*heightBlend=*/true);

            // The entire justification for packing height into ORM alpha: the sample count is
            // unchanged. If this ever regresses, the story's cost argument is void.
            const size_t expectedFetches = detail ? 4u : 2u;
            CHECK(countOccurrences(linear, "textureGrad(") == expectedFetches);
            CHECK(countOccurrences(height, "textureGrad(") == expectedFetches);

            // Height must never change WHICH layers survive: the cull still tests the raw weight.
            CHECK(height.find("if (w < 0.001) continue;") != std::string::npos);
            CHECK(height.find("if (bw") == std::string::npos);

            // The ORM fetch is widened in place (.rgb -> .rgba), not duplicated.
            CHECK(countOccurrences(height, "vec4 ormSample") == 1u);
            CHECK(countOccurrences(height, "ormSample.a") == 1u);
            CHECK(height.find("exp2(") != std::string::npos);
            CHECK(height.find("heightBlendContrast") != std::string::npos);

            // ...and none of it leaks into the linear arm.
            CHECK(linear.find("exp2(") == std::string::npos);
            CHECK(linear.find("vec4 ormSample") == std::string::npos);
            CHECK(linear.find("heightBlendContrast") == std::string::npos);

            // No new branch. Control flow must stay exactly as divergent as before or the
            // explicit-gradient (textureGrad) contract the composite documents is broken.
            CHECK(countOccurrences(height, "if (") == countOccurrences(linear, "if ("));
            CHECK(countOccurrences(height, "continue;") == countOccurrences(linear, "continue;"));
        }
    }

    TEST_CASE("every accumulator in the height arm uses the sharpened weight")
    {
        // The two emission accumulators sit inside an `if (emissionIdx > 0u)` block, visually
        // separated from the main accumulation group. If one kept `* w` while ls_TotalW summed
        // `bw`, emission would be normalized by the wrong denominator and drift with height -
        // silently, and only on emissive terrain layers.
        for (bool detail : {false, true})
        {
            CAPTURE(detail);
            const std::string height = buildTerrainCompositeLoop(detail, /*heightBlend=*/true);
            const std::regex accumulate(R"(ls_\w+ \+=)");

            size_t checked = 0;
            for (const std::string& line : splitLines(height))
            {
                if (!std::regex_search(line, accumulate)) continue;
                ++checked;
                // doctest cannot decompose `||`, so fold it first.
                const bool usesSharpenedWeight = line.find("* bw;") != std::string::npos ||
                                                 line.find("+= bw;") != std::string::npos;
                CHECK_MESSAGE(usesSharpenedWeight,
                              "accumulator does not use the sharpened weight: [" << line << "]");
            }
            // detail: albedo, normal, roughness, metallic, ao, emission, totalW + 2 emission paths.
            CHECK(checked == (detail ? 9u : 6u));
        }
    }

    TEST_CASE("the snippet is a flat, total chain over all four composite permutations")
    {
        // VK-1611/VK-1612 took the emitter from two macros to four. A four-deep #ifdef nest would
        // have been 16 arms at four levels of indentation; the emitter writes a FLAT
        // #if / 14x #elif / #else chain instead, in which every arm names all four macros
        // explicitly. Totality then comes from the #else rather than from counting braces, so no
        // combination can fall through and leave mat_albedo undeclared.
        const std::string snippet = buildTerrainCompositeSnippet();

        CHECK(countOccurrences(snippet, "\n#if ") + (snippet.rfind("#if ", 0) == 0 ? 1u : 0u) == 1u);
        CHECK(countOccurrences(snippet, "#elif ") == 14u);
        CHECK(countOccurrences(snippet, "\n#else\n") == 1u);

        // Every arm body appears, exactly once.
        for (unsigned mask = 0; mask < 16u; ++mask)
        {
            const std::string arm = buildTerrainCompositeLoop((mask & 1u) != 0, (mask & 2u) != 0,
                                                              (mask & 4u) != 0, (mask & 8u) != 0);
            CAPTURE(mask);
            CHECK(countOccurrences(snippet, arm) == 1u);
        }

        // Macro variation is gated too, but OUTSIDE the chain — that is what keeps it from
        // doubling the arm count, and what keeps buildTerrainCompositeLoop (and therefore the
        // golden strings) untouched by it.
        CHECK(countOccurrences(snippet, "#ifdef TERRAIN_MACRO_VARIATION") == 1u);
        CHECK(countOccurrences(snippet, "terrainValueNoise2D") == 2u);
        const size_t chainEnd = snippet.rfind("#ifdef TERRAIN_MACRO_VARIATION");
        REQUIRE(chainEnd != std::string::npos);
        CHECK_MESSAGE(snippet.find("terrainValueNoise2D") > chainEnd,
                      "macro variation leaked into an arm body instead of the tail");
    }

    // ------------------------------------------------------------------
    // 3. The checked-in generated file matches the emitter.
    // ------------------------------------------------------------------

    TEST_CASE("checked-in terrain_material_generated.glsl matches the emitter")
    {
        // The file is CONTENT: the editor regenerates it on Compile and it is committed. Before
        // VK-1609 it had drifted - three comment lines had been hand-added that the generator never
        // emitted - so "regenerate and diff" showed spurious deletions. This keeps it honest.
        const fs::path path =
            repoRoot() / "resources" / "shaders" / "material" / "terrain_material_generated.glsl";
        REQUIRE_MESSAGE(fs::exists(path), "missing " << path.string());

        const std::string onDisk = normalizeNewlines(repo_scan::readFile(path));
        const std::string snippet = buildTerrainCompositeSnippet();

        // The two leading provenance comments carry the material's layer count, so only the body
        // is emitter-determined. Assert the file ENDS with exactly the emitted snippet.
        CHECK_MESSAGE(onDisk.size() >= snippet.size(), "generated file is shorter than the emitter output");
        if (onDisk.size() >= snippet.size())
        {
            const std::string tail = onDisk.substr(onDisk.size() - snippet.size());
            checkTextEqual(tail, snippet);
        }
        CHECK(onDisk.rfind("// Generated terrain material shader code\n", 0) == 0);
    }

    // ------------------------------------------------------------------
    // 4. All four permutations compile to SPIR-V.
    // ------------------------------------------------------------------

    TEST_CASE("terrain_rvt_bake.glsl compiles in every composite permutation")
    {
        // terrain_rvt_bake.glsl is plain VERTEX + FRAGMENT (no mesh-shader extension) and
        // #includes the generated composite, so it is the one shader in the terrain path that a
        // CPU-only suite can drive end to end. mesh_terrain.glsl needs GL_EXT_mesh_shader and the
        // full 14-set layout, so it stays out of scope here.
        const fs::path shaderDir = repoRoot() / "resources" / "shaders" / "gpudriven";
        const fs::path shaderPath = shaderDir / "terrain_rvt_bake.glsl";
        REQUIRE_MESSAGE(fs::exists(shaderPath), "missing " << shaderPath.string());

        const auto stages = resource::ShaderResource::readShaderFile(shaderPath.string());
        REQUIRE_MESSAGE(!stages.empty(), "no #type stages parsed from " << shaderPath.string());

        // Five independent macros: the four arm-selecting ones plus VK-1611's macro-variation
        // tail, which is gated separately. 32 combinations x 2 stages. This is by far the
        // highest-value case in the file — it compiles the REAL bake shader against the REAL
        // generated composite and gpu_types.glsl, so a contract variable an includer forgot to
        // define, or a struct field added on only one side, fails here with no GPU involved.
        static constexpr const char* MACROS[] = {
            "TERRAIN_DETAIL_MAPS",
            "TERRAIN_HEIGHT_BLEND",
            "TERRAIN_DISTANCE_RESCALE",
            "TERRAIN_HEX_TILING",
            "TERRAIN_MACRO_VARIATION",
        };
        constexpr unsigned MACRO_COUNT = 5;

        for (unsigned mask = 0; mask < (1u << MACRO_COUNT); ++mask)
        {
            CAPTURE(mask);

            shaderCompiler::CompileOptions options;
            options.includeBasePath = shaderDir;
            std::string suffix;
            for (unsigned bit = 0; bit < MACRO_COUNT; ++bit)
            {
                if ((mask & (1u << bit)) != 0)
                {
                    options.macroNames.push_back(MACROS[bit]);
                    suffix += "+";
                    suffix += MACROS[bit];
                }
            }

            bool sawVertex = false;
            bool sawFragment = false;
            for (const auto& stage : stages)
            {
                sawVertex = sawVertex || stage.type == resource::ShaderType::VERTEX;
                sawFragment = sawFragment || stage.type == resource::ShaderType::FRAGMENT;

                const auto vkStage =
                    shaderCompiler::shaderTypeToVulkanStage(static_cast<uint8_t>(stage.type));
                const std::string name = "terrain_rvt_bake.glsl:" +
                                         std::to_string(static_cast<int>(stage.type)) + suffix;

                // compile() returns an empty vector and logs on failure.
                const auto spirv = shaderCompiler::compile(stage.source, vkStage, name, options);
                CHECK_MESSAGE(!spirv.empty(), "failed to compile " << name);
            }
            CHECK(sawVertex);
            CHECK(sawFragment);
        }
    }

    // ------------------------------------------------------------------
    // 5. The blend arithmetic.
    // ------------------------------------------------------------------

    TEST_CASE("contrast 0 returns the weight with an identical bit pattern")
    {
        // THE acceptance criterion, in executable form. Note `==` on floats is deliberate here:
        // doctest::Approx would pass on a value that shifts pixels.
        const float weights[] = {0.001f, 0.0011f, 0.005f, 0.02f, 0.1f, 0.25f, 0.5f, 0.75f, 1.0f,
                                 0.333333f, 0.987654f, 1e-6f, 1e-30f};
        const float heights[] = {0.0f, 0.001f, 0.25f, 0.5f, 0.75f, 1.0f};

        for (float w : weights)
        {
            for (float h : heights)
            {
                const float got = terrain::heightBlendWeight(w, h, 0.0f);
                CAPTURE(w);
                CAPTURE(h);
                CHECK(got == w);
                // Bit-pattern check, so a -0.0f / +0.0f style difference cannot slip through.
                CHECK(std::memcmp(&got, &w, sizeof(float)) == 0);
            }
        }
    }

    TEST_CASE("the contrast clamp keeps the sharpening factor finite and bounded")
    {
        // MAX_HEIGHT_BLEND_CONTRAST is a correctness invariant, not a taste limit: the linear
        // fallback multiplies the sharpening factor by exactly 0.0, and 0.0 * infinity is NaN.
        const float c = terrain::MAX_HEIGHT_BLEND_CONTRAST;
        const float limit = std::exp2(c * 0.5f); // == 256 at the current bound

        for (float h : {0.0f, 0.5f, 1.0f})
        {
            for (float w : {0.05f, 0.5f, 1.0f})
            {
                const float got = terrain::heightBlendWeight(w, h, c);
                CAPTURE(w);
                CAPTURE(h);
                CHECK(std::isfinite(got));
                CHECK(got >= w / limit - 1e-6f);
                CHECK(got <= w * limit + 1e-6f);
            }
        }
        CHECK(limit == doctest::Approx(256.0f));
    }

    TEST_CASE("raising a layer's height raises its share of the blend")
    {
        // Two layers with equal splat weight: the taller one must win, and win harder as contrast
        // rises. This is the whole visual point of the story.
        const float w = 0.5f;
        float previousShare = 0.0f;
        for (float contrast : {1.0f, 2.0f, 4.0f, 8.0f, 16.0f})
        {
            const float tall = terrain::heightBlendWeight(w, 0.9f, contrast);
            const float low = terrain::heightBlendWeight(w, 0.1f, contrast);
            const float share = tall / (tall + low);
            CAPTURE(contrast);
            CHECK(share > 0.5f);
            CHECK(share > previousShare);
            previousShare = share;
        }
    }

    TEST_CASE("equal heights normalize back to the linear blend")
    {
        // Every ORM produced before VK-1609 has a constant alpha, so this is the real-world case:
        // a common factor must cancel under normalization and leave the picture unchanged.
        const float contrast = 8.0f;
        const float wA = 0.7f, wB = 0.3f, h = 1.0f;
        const float a = terrain::heightBlendWeight(wA, h, contrast);
        const float b = terrain::heightBlendWeight(wB, h, contrast);
        CHECK(a / (a + b) == doctest::Approx(wA / (wA + wB)));
    }

    TEST_CASE("sharpening fades out at the composite's weight cull")
    {
        // The generated loop drops a layer at w < 0.001. Without the fade, a layer just above that
        // cull carrying high height would contribute a large share and then vanish, drawing a hard
        // contour ring along the w = 0.001 iso-line.
        const float contrast = terrain::MAX_HEIGHT_BLEND_CONTRAST;
        const float atCull = terrain::heightBlendWeight(terrain::HEIGHT_BLEND_FADE_MIN, 1.0f, contrast);
        CHECK(atCull == terrain::HEIGHT_BLEND_FADE_MIN); // fully faded: exactly the raw weight

        const float justAbove = terrain::heightBlendWeight(0.00101f, 1.0f, contrast);
        CHECK(justAbove < 0.00101f * 1.05f); // still essentially unsharpened

        // ...and past the fade window the sharpening is at full strength.
        const float beyond = terrain::heightBlendWeight(terrain::HEIGHT_BLEND_FADE_MAX, 1.0f, contrast);
        CHECK(beyond == doctest::Approx(terrain::HEIGHT_BLEND_FADE_MAX * std::exp2(contrast * 0.5f)));
    }

    // ------------------------------------------------------------------
    // 6. Resolver mapping - where authoring intent becomes a GPU scalar.
    // ------------------------------------------------------------------

    TEST_CASE("resolveTerrainLayerPBR gates the height contrast on mode AND a packed ORM")
    {
        terrain::TerrainMaterialLayer layer;
        layer.heightContrast = 6.0f;

        render::mesh::ExtractedPBRValues withOrm;
        withOrm.materialPath = "fake.vfMat";
        withOrm.ormTexturePath = "rock_orm.vfImage";

        render::mesh::ExtractedPBRValues withoutOrm;
        withoutOrm.materialPath = "fake.vfMat";
        withoutOrm.albedoTexturePath = "rock_albedo.vfImage";

        SUBCASE("Linear mode never height-blends, whatever the contrast says")
        {
            layer.blendMode = terrain::TerrainLayerBlendMode::Linear;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, &withOrm).heightBlendContrast == 0.0f);
        }

        SUBCASE("HeightBlend with a packed ORM passes the contrast through")
        {
            layer.blendMode = terrain::TerrainLayerBlendMode::HeightBlend;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, &withOrm).heightBlendContrast
                  == doctest::Approx(6.0f));
        }

        SUBCASE("HeightBlend WITHOUT an ORM falls back to exactly linear")
        {
            // Height rides ORM alpha, so no ORM means no height source at all. Uploading exactly
            // 0.0f is what makes this layer bit-identical to the pre-VK-1609 composite.
            layer.blendMode = terrain::TerrainLayerBlendMode::HeightBlend;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, &withoutOrm).heightBlendContrast == 0.0f);
        }

        SUBCASE("no material at all falls back to exactly linear")
        {
            layer.blendMode = terrain::TerrainLayerBlendMode::HeightBlend;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, nullptr).heightBlendContrast == 0.0f);
        }

        SUBCASE("the contrast is clamped to the exp2-safe range")
        {
            layer.blendMode = terrain::TerrainLayerBlendMode::HeightBlend;

            layer.heightContrast = 1000.0f;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, &withOrm).heightBlendContrast
                  == doctest::Approx(terrain::MAX_HEIGHT_BLEND_CONTRAST));

            layer.heightContrast = -5.0f;
            CHECK(render::gpudriven::resolveTerrainLayerPBR(layer, &withOrm).heightBlendContrast == 0.0f);
        }
    }

    // ------------------------------------------------------------------
    // 7. C++ / GLSL ABI mirror.
    // ------------------------------------------------------------------

    TEST_CASE("TerrainLayerGPUData layout is what the shader and the SSBO stride assume")
    {
        using render::gpudriven::TerrainLayerGPUData;
        // Mirrors the static_asserts as named cases, so a failure reads as a diagnosis rather
        // than a wall of compiler output.
        CHECK(sizeof(TerrainLayerGPUData) == 64); // VK-1612 grew it from 48
        CHECK(alignof(TerrainLayerGPUData) == 4);
        CHECK(sizeof(TerrainLayerGPUData) % 16 == 0);
        CHECK(offsetof(TerrainLayerGPUData, heightBlendContrast) == 36);
        // VK-1614 consumed VK-1609's reservation IN PLACE. These two offsets and the size above are
        // the whole "no second ABI bump" claim: the story renamed the fields and started writing
        // them, and changed nothing about the layout. If either moves, the claim is false.
        CHECK(offsetof(TerrainLayerGPUData, layerPorosity) == 40);
        CHECK(offsetof(TerrainLayerGPUData, layerSnowRetention) == 44);
        CHECK(offsetof(TerrainLayerGPUData, hexTilingStrength) == 48);
        CHECK(offsetof(TerrainLayerGPUData, hexCellScale) == 52);
        CHECK(offsetof(TerrainLayerGPUData, hexContrast) == 56);
        CHECK(offsetof(TerrainLayerGPUData, hexRotationStrength) == 60);
    }

    TEST_CASE("TerrainAntiTilingGPUData layout matches its GLSL mirror")
    {
        using render::gpudriven::TerrainAntiTilingGPUData;
        // VK-1611's material-global block. Small, but it lives on a descriptor binding BOTH the
        // live terrain pipeline and the RVT bake pipeline read, so a layout slip corrupts baked
        // pages and the live fallback in different ways.
        CHECK(sizeof(TerrainAntiTilingGPUData) == 32);
        CHECK(alignof(TerrainAntiTilingGPUData) == 4);
        CHECK(sizeof(TerrainAntiTilingGPUData) % 16 == 0);
        CHECK(offsetof(TerrainAntiTilingGPUData, macroSeed) == 12);
        CHECK(offsetof(TerrainAntiTilingGPUData, rescaleStrength) == 16);
        CHECK(offsetof(TerrainAntiTilingGPUData, rescaleWidthLog2) == 28);
    }

    TEST_CASE("gpu_types.glsl mirrors TerrainLayerGPUData field for field")
    {
        // Nothing else in the repo checks this. A one-sided edit to either side silently
        // reinterprets every terrain layer on the GPU.
        const fs::path path = repoRoot() / "resources" / "shaders" / "common" / "gpu_types.glsl";
        const std::string src = repo_scan::readFile(path);
        REQUIRE_MESSAGE(!src.empty(), "missing " << path.string());

        const size_t begin = src.find("struct TerrainLayerGPUData");
        REQUIRE(begin != std::string::npos);
        const size_t open = src.find('{', begin);
        const size_t close = src.find("};", open);
        REQUIRE(open != std::string::npos);
        REQUIRE(close != std::string::npos);
        const std::string body = src.substr(open + 1, close - open - 1);

        const std::vector<std::pair<std::string, std::string>> expected = {
            {"uint",  "albedoTextureIndex"},
            {"uint",  "normalTextureIndex"},
            {"float", "tilingScale"},
            {"uint",  "ormTextureIndex"},
            {"float", "roughness"},
            {"float", "metallic"},
            {"float", "ao"},
            {"float", "emissionStrength"},
            {"uint",  "emissionTextureIndex"},
            {"float", "heightBlendContrast"},
            {"float", "layerPorosity"},
            {"float", "layerSnowRetention"},
            {"float", "hexTilingStrength"},
            {"float", "hexCellScale"},
            {"float", "hexContrast"},
            {"float", "hexRotationStrength"},
        };

        const std::regex field(R"((uint|float|int)\s+(\w+)\s*;)");
        std::vector<std::pair<std::string, std::string>> found;
        for (auto it = std::sregex_iterator(body.begin(), body.end(), field);
             it != std::sregex_iterator(); ++it)
        {
            found.emplace_back((*it)[1].str(), (*it)[2].str());
        }

        REQUIRE(found.size() == expected.size());
        for (size_t i = 0; i < expected.size(); ++i)
        {
            CHECK_MESSAGE(found[i].first == expected[i].first,
                          "field " << i << " type: " << found[i].first << " != " << expected[i].first);
            CHECK_MESSAGE(found[i].second == expected[i].second,
                          "field " << i << " name: " << found[i].second << " != " << expected[i].second);
        }
        // Every member is a 4-byte scalar, which is what makes the std430 array stride equal
        // sizeof. A vec2/vec3/vec4 here would desync C++ and GLSL silently.
        CHECK(4 * found.size() == sizeof(render::gpudriven::TerrainLayerGPUData));
    }
}

TEST_SUITE("OrmTexturePackerHeight")
{
    TEST_CASE("no height input packs the neutral default into alpha at every mip")
    {
        const std::vector<uint8_t> ao(4 * 4, 200);
        const auto aoTex = makeGray(4, 4, ao);
        const auto out = fs::temp_directory_path() / "vf_test_orm_no_height.vfImage";

        const auto result = texture::OrmTexturePacker::packORMFromData(
            &aoTex, nullptr, nullptr, nullptr, out.string());
        REQUIRE_MESSAGE(result.success, result.errorMessage);

        const auto mips = readVfImageMips(out);
        REQUIRE(mips.size() == 3); // 4x4 -> 2x2 -> 1x1
        for (const auto& mip : mips)
        {
            for (size_t i = 3; i < mip.bgra.size(); i += 4)
            {
                REQUIRE(mip.bgra[i] == texture::OrmTexturePacker::DEFAULT_HEIGHT);
            }
        }
        fs::remove(out);
    }

    TEST_CASE("a height input lands in alpha and survives mip generation")
    {
        // THE regression test for the bug this story fixed: sampleBoxFilter used to force alpha to
        // 255 at every level, so height existed at mip 0 only. On terrain, essentially everything
        // beyond a few metres samples mip >= 1, so height blending would have worked in a small
        // bubble around the camera and reverted to a linear blend at distance - a failure that
        // reads as a shader bug, not an asset one, and is only visible on a GPU at range.
        //
        // 2x2 heights chosen so the box average is exact and distinctive.
        const std::vector<uint8_t> heights = {0, 100, 200, 240}; // mean = 135
        const auto heightTex = makeGray(2, 2, heights);
        const std::vector<uint8_t> ao(2 * 2, 250);
        const auto aoTex = makeGray(2, 2, ao);
        const auto out = fs::temp_directory_path() / "vf_test_orm_with_height.vfImage";

        const auto result = texture::OrmTexturePacker::packORMFromData(
            &aoTex, nullptr, nullptr, &heightTex, out.string());
        REQUIRE_MESSAGE(result.success, result.errorMessage);

        const auto mips = readVfImageMips(out);
        REQUIRE(mips.size() == 2); // 2x2 -> 1x1

        // Mip 0: alpha is the source height, texel for texel.
        REQUIRE(mips[0].bgra.size() == 2 * 2 * 4);
        for (size_t t = 0; t < heights.size(); ++t)
        {
            CHECK(mips[0].bgra[t * 4 + 3] == heights[t]);
        }
        // ...and AO still occupies red. The BGRA-on-disk swizzle must not have touched alpha.
        CHECK(mips[0].bgra[2] == 250);

        // Mip 1: alpha is the 2x2 box average, NOT 255.
        REQUIRE(mips[1].bgra.size() == 4);
        CHECK(mips[1].bgra[3] == (0u + 100u + 200u + 240u) / 4u);
        CHECK(mips[1].bgra[3] != 255);

        fs::remove(out);
    }

    TEST_CASE("a height texture alone is enough to determine the output size")
    {
        const std::vector<uint8_t> heights(2 * 2, 77);
        const auto heightTex = makeGray(2, 2, heights);
        const auto out = fs::temp_directory_path() / "vf_test_orm_height_only.vfImage";

        const auto result = texture::OrmTexturePacker::packORMFromData(
            nullptr, nullptr, nullptr, &heightTex, out.string());
        REQUIRE_MESSAGE(result.success, result.errorMessage);

        const auto mips = readVfImageMips(out);
        REQUIRE(!mips.empty());
        CHECK(mips[0].width == 2);
        CHECK(mips[0].bgra[3] == 77);
        // The other channels fall back to their documented defaults (on disk: B, G, R).
        CHECK(mips[0].bgra[2] == texture::OrmTexturePacker::DEFAULT_AO);
        CHECK(mips[0].bgra[1] == texture::OrmTexturePacker::DEFAULT_ROUGHNESS);
        CHECK(mips[0].bgra[0] == texture::OrmTexturePacker::DEFAULT_METALLIC);

        fs::remove(out);
    }
}
