#pragma once

#include <glm/glm.hpp>
#include <cstdint>

namespace render::vegetation
{
    // Per grass blade instance (generated by compute shader)
    struct GrassInstanceGPU
    {
        glm::vec4 positionAndRotation;  // xyz=world position, w=Y rotation
        glm::vec4 scaleAndDensity;      // x=height, y=width, z=density, w=windPhase
        glm::vec4 color;                // xyz=color tint, w=alpha
    };

    // Per-tile vegetation metadata for GPU
    struct VegetationTileGPUData
    {
        glm::ivec2 tileCoord;
        uint32_t grassInstanceOffset;
        uint32_t grassInstanceCount;
        uint32_t padding0;
        uint32_t padding1;
        glm::vec4 boundingSphere;       // xyz=center, w=radius
        glm::vec4 aabbMin;
        glm::vec4 aabbMax;
    };

    // Constants
    static constexpr uint32_t MAX_GRASS_INSTANCES_PER_TILE = 65536;
    static constexpr uint32_t MAX_VEGETATION_TILES = 256;
}
