#include "OffMeshLinkDrawer.hpp"
#include "events/EventDispatcher.hpp"
#include "events/scene/ComponentPhysicsLightEvents.hpp"
#include "scene/EntityRegistry.hpp"
#include "../../../services/data/EntityConversion.hpp"
#include "components/Components.hpp"
#include <imgui.h>

namespace windows::details
{
    static const char* linkTypeNames[] = {"Jump", "Climb", "Drop", "Custom"};
    static const char* directionNames[] = {"One-Way", "Bidirectional"};

    bool OffMeshLinkDrawer::draw(services::EntityHandle handle)
    {
        auto& registry = scene::EntityRegistry::getRegistry();
        auto entity = services::internal::fromHandle(handle);

        if (!registry.valid(entity) || !registry.all_of<components::OffMeshLinkComponent>(entity))
        {
            return false;
        }

        auto& link = registry.get<components::OffMeshLinkComponent>(entity);

        bool open = true;
        if (ImGui::CollapsingHeader("Off-Mesh Link", &open, ImGuiTreeNodeFlags_DefaultOpen))
        {
            ImGui::Indent();

            ImGui::Text("Link Type");
            ImGui::PushItemWidth(-1);
            int typeIdx = static_cast<int>(link.linkType);
            if (ImGui::Combo("##OffMeshLinkType", &typeIdx, linkTypeNames, IM_ARRAYSIZE(linkTypeNames)))
            {
                link.linkType = static_cast<components::OffMeshLinkType>(typeIdx);
            }
            ImGui::PopItemWidth();

            ImGui::Spacing();
            ImGui::Text("Direction");
            ImGui::PushItemWidth(-1);
            int dirIdx = static_cast<int>(link.direction);
            if (ImGui::Combo("##OffMeshLinkDir", &dirIdx, directionNames, IM_ARRAYSIZE(directionNames)))
            {
                link.direction = static_cast<components::OffMeshLinkDirection>(dirIdx);
            }
            ImGui::PopItemWidth();

            ImGui::Spacing();
            ImGui::Text("Endpoints (Local Offset)");
            ImGui::PushItemWidth(-1);
            ImGui::DragFloat3("##OffMeshStart", &link.startOffset.x, 0.1f, -1000.0f, 1000.0f, "Start: %.1f");
            ImGui::DragFloat3("##OffMeshEnd", &link.endOffset.x, 0.1f, -1000.0f, 1000.0f, "End: %.1f");
            ImGui::PopItemWidth();

            ImGui::Spacing();
            ImGui::Text("Properties");
            ImGui::PushItemWidth(-1);
            ImGui::DragFloat("##OffMeshRadius", &link.radius, 0.01f, 0.1f, 5.0f, "Radius: %.2f");
            ImGui::DragFloat("##OffMeshCost", &link.costModifier, 0.1f, 0.1f, 100.0f, "Cost: %.1f");
            ImGui::PopItemWidth();

            if (link.autoGenerated)
            {
                ImGui::Spacing();
                ImGui::TextColored(ImVec4(0.7f, 0.7f, 0.0f, 1.0f), "Auto-generated");
            }

            ImGui::Unindent();
        }

        if (!open)
        {
            events::scene::RemoveOffMeshLinkComponentCommand cmd;
            cmd.entity = handle;
            events::EventDispatcher::instance().execute(cmd);
            return false;
        }

        return true;
    }
}
