#pragma once
#include <string>
#include <cstdint>

namespace types
{
    // Area type constants
    constexpr uint8_t NAVMESH_AREA_GROUND = 0;
    constexpr uint8_t NAVMESH_AREA_JUMP = 1;
    constexpr uint8_t NAVMESH_AREA_CLIMB = 2;
    constexpr uint8_t NAVMESH_AREA_DROP = 3;
    constexpr uint8_t NAVMESH_AREA_CUSTOM = 4;
    constexpr uint8_t NAVMESH_AREA_ROAD = 5;
    constexpr uint8_t NAVMESH_AREA_GRASS = 6;
    constexpr uint8_t NAVMESH_AREA_MUD = 7;
    constexpr uint8_t NAVMESH_AREA_WATER = 8;
    constexpr uint8_t NAVMESH_AREA_HAZARD = 9;
    constexpr uint8_t NAVMESH_MAX_AREAS = 64;
    constexpr int NAVMESH_NAMED_AREA_COUNT = 10;

    inline const char* getNavmeshAreaName(uint8_t area)
    {
        static const char* names[] = {
            "Ground", "Jump", "Climb", "Drop", "Custom",
            "Road", "Grass", "Mud", "Water", "Hazard"
        };
        if (area < NAVMESH_NAMED_AREA_COUNT)
            return names[area];
        return "User";
    }

    struct NavmeshBakeSettings
    {
        // Rasterization
        float cellSize = 0.25f;
        float cellHeight = 0.2f;

        // Agent
        float agentRadius = 0.25f;
        float agentHeight = 2.0f;
        float agentMaxClimb = 0.4f;
        float agentMaxSlope = 45.0f;

        // Region
        int regionMinSize = 8;
        int regionMergeSize = 20;

        // Polygonization
        float edgeMaxLen = 12.0f;
        float edgeMaxError = 1.3f;
        int vertsPerPoly = 6;

        // Detail mesh
        float detailSampleDist = 6.0f;
        float detailSampleMaxError = 1.0f;

        // Tile size (in cells)
        int tileSize = 128;

        // Geometry collection
        bool includeStaticMeshes = true;
        bool includeTerrain = true;
        bool includeColliders = true;

        // Area cost multipliers (indexed by area ID, 0-63)
        float areaCosts[64] = {
            1.0f,  // 0: Ground
            2.0f,  // 1: Jump
            3.0f,  // 2: Climb
            1.5f,  // 3: Drop
            1.0f,  // 4: Custom
            0.5f,  // 5: Road
            1.0f,  // 6: Grass
            3.0f,  // 7: Mud
            5.0f,  // 8: Water
            10.0f, // 9: Hazard
            // 10-63: default 1.0f (zero-initialized, set in constructor)
        };

        // Auto-generation
        bool autoGenerateDropLinks = false;
        float autoDropMaxHeight = 4.0f;
        float autoDropMinHeight = 0.5f;

        // Hierarchical pathfinding
        float hierarchicalPathThreshold = 96.0f;

        NavmeshBakeSettings()
        {
            for (int i = NAVMESH_NAMED_AREA_COUNT; i < 64; ++i)
                areaCosts[i] = 1.0f;
        }
    };

    enum class NavmeshBakeStatus : uint8_t
    {
        Idle = 0,
        Collecting,
        Voxelizing,
        Building,
        Complete,
        Failed
    };

    struct NavmeshBakeProgress
    {
        NavmeshBakeStatus status = NavmeshBakeStatus::Idle;
        float progress = 0.0f;
        std::string currentStage;
    };
}
