#pragma once
#include <string>
#include <cstdint>

namespace types
{
    // Area type constants for off-mesh links
    constexpr uint8_t NAVMESH_AREA_GROUND = 0;
    constexpr uint8_t NAVMESH_AREA_JUMP = 1;
    constexpr uint8_t NAVMESH_AREA_CLIMB = 2;
    constexpr uint8_t NAVMESH_AREA_DROP = 3;
    constexpr uint8_t NAVMESH_AREA_CUSTOM = 4;

    struct NavmeshBakeSettings
    {
        // Rasterization
        float cellSize = 0.25f;
        float cellHeight = 0.2f;

        // Agent
        float agentRadius = 0.25f;
        float agentHeight = 2.0f;
        float agentMaxClimb = 0.4f;
        float agentMaxSlope = 45.0f;

        // Region
        int regionMinSize = 8;
        int regionMergeSize = 20;

        // Polygonization
        float edgeMaxLen = 12.0f;
        float edgeMaxError = 1.3f;
        int vertsPerPoly = 6;

        // Detail mesh
        float detailSampleDist = 6.0f;
        float detailSampleMaxError = 1.0f;

        // Tile size (in cells)
        int tileSize = 128;

        // Geometry collection
        bool includeStaticMeshes = true;
        bool includeTerrain = true;
        bool includeColliders = true;

        // Off-mesh link cost modifiers
        float jumpCost = 2.0f;
        float climbCost = 3.0f;
        float dropCost = 1.5f;
        float customLinkCost = 1.0f;

        // Auto-generation
        bool autoGenerateDropLinks = false;
        float autoDropMaxHeight = 4.0f;
        float autoDropMinHeight = 0.5f;
    };

    enum class NavmeshBakeStatus : uint8_t
    {
        Idle = 0,
        Collecting,
        Voxelizing,
        Building,
        Complete,
        Failed
    };

    struct NavmeshBakeProgress
    {
        NavmeshBakeStatus status = NavmeshBakeStatus::Idle;
        float progress = 0.0f;
        std::string currentStage;
    };
}
